language: ruby
rvm:
  - 2.1.10
  - 1.9.3
  - 2.2.6
  - 2.3.3
  - 2.4.0
  - jruby-19mode
  - jruby-head
  - ruby-head
  - rbx
install: gem install minitest
before_script:
  - gem build ci_uy.gemspec
  - gem install ci_uy
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx